# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - flwins-webapp-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_AZURE_AD_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AD_AUTHORITY: ${{ secrets.NEXT_PUBLIC_AZURE_AD_AUTHORITY }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
          NEXT_PUBLIC_KNOWN_AUTHORITY: ${{ secrets.NEXT_PUBLIC_KNOWN_AUTHORITY }}
          NEXT_PUBLIC_AUTHORITY_DOMAIN: ${{ secrets.NEXT_PUBLIC_AUTHORITY_DOMAIN }}
          NEXT_PUBLIC_SIGN_UP_SIGN_IN_POLICY: ${{ secrets.NEXT_PUBLIC_SIGN_UP_SIGN_IN_POLICY }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C57582F39E042C2BBCF4DFAF85C461B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C5AFCF37115446D949BCCAC9BE06E04 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_19ACDDAB21154634875E875ACFCDC3CC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flwins-webapp-dev'
          slot-name: 'Production'
          package: .
      
      - name: 'Set Azure Web App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'flwins-webapp-dev'
          slot-name: 'Production'
          app-settings-json: |
            [
              {
                "name": "NEXT_PUBLIC_AZURE_AD_CLIENT_ID",
                "value": "${{ secrets.NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}"
              },
              {
                "name": "NEXT_PUBLIC_AZURE_AD_AUTHORITY", 
                "value": "${{ secrets.NEXT_PUBLIC_AZURE_AD_AUTHORITY }}"
              },
              {
                "name": "NEXT_PUBLIC_REDIRECT_URI",
                "value": "${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}"
              },
              {
                "name": "NEXT_PUBLIC_KNOWN_AUTHORITY",
                "value": "${{ secrets.NEXT_PUBLIC_KNOWN_AUTHORITY }}"
              },
              {
                "name": "NEXT_PUBLIC_AUTHORITY_DOMAIN",
                "value": "${{ secrets.NEXT_PUBLIC_AUTHORITY_DOMAIN }}"
              },
              {
                "name": "NEXT_PUBLIC_SIGN_UP_SIGN_IN_POLICY",
                "value": "${{ secrets.NEXT_PUBLIC_SIGN_UP_SIGN_IN_POLICY }}"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~22"
              }
            ]
          